sources:
   - name: dbt_yml_files
     database: dbt_yml_files
     schema: gz_raw_data
     loader: bigquery
     description: gz_raw_data
     freshness:
     tables:
       - name: raw_gz_sales
         identifier: raw_gz_sales
       - name: raw_gz_product
         identifier: raw_gz_product
       - name: raw_gz_ship
         identifier: raw_gz_ship