sources:
   - name: raw
     database: data-analytics-sql-485211
     schema: gz_raw_data
     loader: bigquery
     description: gz_raw_data
     tables:
       - name: sales
         identifier: raw_gz_sales
       - name: product
         identifier: raw_gz_product
       - name: ship
         identifier: raw_gz_ship